import './globals.css';

import { Inter } from 'next/font/google';
import { cn } from '~/lib/cn';

const inter = Inter({ subsets: ['latin', 'cyrillic-ext'], weight: ['500', '900'] });

export const metadata = {
  title: 'Contourify',
  description: 'Generated by create next app'
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-black text-white')}>{props.children}</body>
    </html>
  );
}
